
Title: Bacterial diversity analysis
Author: Teeratat Kaewjon
Updated: 5/18/2024
---
output:
  word_document: default
  html_document: default
---

```{r warning=FALSE, message=FALSE}
library(ape)
library(vegan)
library(plyr)
library(dplyr)
library(scales)
library(grid)
library(reshape2)
library(phyloseq)
library(magrittr)                        
library(ggplot2)
library(ggpubr)
library(data.table)
library(tidyr)
library(tidyverse)
library(multcompView)
library(car)
library(microViz)
```

```{r}
###Input 16S 
otus.bac <- read.table("D:/Biocrust_Reawakening/Github/Bacteria(16S)/Data/CrustTemp216SasvUN3.asv_table_fix.txt", header = TRUE, sep = "\t", row.names = 1)
colnames(otus.bac) <- gsub("X", "", colnames(otus.bac))  # Remove "X" from all column names
otumat16s <- as.matrix(otus.bac)
OTU16s <- otu_table(otumat16s, taxa_are_rows = TRUE)
```

```{r}
taxmat16s <- read.table("D:/Biocrust_Reawakening/Github/Bacteria(16S)/Data/CrustTemp216SasvUN3.taxonomy_file_fix.txt", header=T,sep="\t",row.names=1)
taxmat16s <- as(as.matrix(taxmat16s),"matrix")
TAX16s <- tax_table(taxmat16s)
```

```{r}
meta16s <- read.table("D:/Biocrust_Reawakening/Github/Bacteria(16S)/Data/CrustTemp216SasvUN3.mapping_file_fix.txt",header=TRUE,row.names=1,sep="\t",stringsAsFactors=FALSE)

sampleData16s <- sample_data(meta16s)
```

```{r}
bac.tree <- read_tree("D:/Biocrust_Reawakening/Github/Bacteria(16S)/Data/tree.nwk")
```

```{r}
physeq16s <- phyloseq(OTU16s,TAX16s,sampleData16s, bac.tree)
physeq16s
```
```{r}

physeq16s <- subset_taxa(physeq16s, Kingdom == "Bacteria")
physeq16s
physeq16s<- subset_taxa(physeq16s.fix, Family != "Mitochondria")
physeq16s
#physeq16s <- subset_taxa(physeq16s, Species != "NA")
#physeq16s <- subset_taxa(physeq16s, Species != "uncultured bacterium")
#physeq16s <- subset_taxa(physeq16s, Species != "metagenome")

physeq16S.prune = prune_taxa(taxa_sums(physeq16s) > 1, physeq16s)
physeq16S.prune
```

Input fixed Taxonomy file and prune singletrons out

```{r}
taxmat16s.fix <- read.table("./Bacteria_data/tax_bac_fix.csv", header=T,sep=",",row.names=1)
taxmat16s.fix <- as(as.matrix(taxmat16s.fix),"matrix")
TAX16s.fix <- tax_table(taxmat16s.fix)
```

```{r}
physeq16s.fix <- phyloseq(OTU16s,TAX16s.fix,sampleData16s, bac.tree)
physeq16s.fix

physeq16s.fix <- subset_taxa(physeq16s.fix, Kingdom == "Bacteria")
physeq16s.fix
physeq16s.fix <- subset_taxa(physeq16s.fix, Family != "Mitochondria")
physeq16s.fix
#physeq16s <- subset_taxa(physeq16s, Species != "NA")
#physeq16s <- subset_taxa(physeq16s, Species != "uncultured bacterium")
#physeq16s <- subset_taxa(physeq16s, Species != "metagenome")

physeq16S.prune = prune_taxa(taxa_sums(physeq16s.fix) > 1, physeq16s.fix)
physeq16S.prune
```

### Beta diversity with NMDS plot analysis

```{r}
sample_data(physeq.LAC)$Incubation = factor(sample_data(physeq.LAC)$Incubation, levels = c("0.05", "1", "24", "48", "96"))

sample_data(physeq.CLC)$Incubation = factor(sample_data(physeq.CLC)$Incubation, levels = c("0.05", "1", "24", "48", "96"))
```

```{r}
physeq_ord <- ordinate(physeq.LAC,method = "NMDS",distance =  "wunifrac")
```

```{r}
ps.dist.all = phyloseq::distance(physeq.LAC, "wunifrac")
```

```{r}
adonis2(ps.dist.all ~Incubation, as(sample_data(physeq.LAC),"data.frame"))
```

```{r}
tiff("D:/Biocrust_Reawakening/New_data/Bacteria/Bac_Beta_CLC_NMDS.tiff", units="in", width = 6, height = 4.5, res = 600 )
plot

pslayer = plot_ordination(physeq.LAC, physeq_ord, type = "samples", color = "Incubation") + ggtitle("Bacterial Beta Diversity of LAC crust type") + 
  annotate("text", x = 0.008, y = .02, label = "PERMANOVA, p = 0.001") +
  geom_point(size=4) + 
  scale_colour_manual(values =  c("#F8766D" , "#A3A500" , "#00BF7D",  "#00B0F6", "#E76BF3")) + 
  theme_pubr(legend = "right", border = TRUE) + 
  theme(plot.title = element_text(hjust = 0.5))

pslayer
```

###Alpha diversity of Phylum

```{r}
physeq.cb = subset_taxa(physeq.LAC, Phylum == "Cyanobacteria")
physeq.cb
```

```{r}
sample_data(physeq.cb)$Incubation = factor(sample_data(physeq.cb)$Incubation, levels = c("0.05", "1", "24", "48", "96"))
```

```{r}
alpha.diversity = estimate_richness(physeq.cb, measures = c("Observed"))
data.anova = cbind(sample_data(physeq.cb), alpha.diversity)
#leveneTest(Observed ~ Incubation, data = data.anova)
physeq.anova = aov(Observed ~ Incubation, data.anova)
summary(physeq.anova)
```

```{r}
tukey.ps = TukeyHSD(x=physeq.anova, 'Incubation', conf.level = 0.95)

generate_label_df <- function(tukey.ps, variable){
 
     # Extract labels and factor levels from Tukey post-hoc 
     Tukey.levels <- tukey.ps[[variable]][,4]
     Tukey.labels <- data.frame(multcompLetters(Tukey.levels)['Letters'])
     
     #I need to put the labels in the same order as in the boxplot :
     Tukey.labels$treatment=rownames(Tukey.labels)
     Tukey.labels=Tukey.labels[order(Tukey.labels$treatment) , ]
     return(Tukey.labels)
     }

LABELS=generate_label_df(tukey.ps, 'Incubation')
names(LABELS) = c('Letters','Incubation')
```

```{r}
LABELS
```

```{r}
ylabel <- data.frame("ylabel" = c(1800, 1800, 1800, 1600, 1600)) #LAC surface
LABELS$ylabel<-ylabel$ylabel
```

```{r}
tiff("D:/Biocrust_Reawakening/New_data/Bacteria/BAC_Alpha_LAC_Observed_Cyanobacteria.tiff", units="in", width = 4.5, height = 6, res = 600 )

#pdf("D:/Biocrust_Reawakening/Github/Fungi(ITS)/Figures/BAC_Alpha_CLC_Shannon.pdf",width = 8.5, height = 5.5)

physeq.plot.richness.incubation = plot_richness(physeq.cb, x="Incubation", color=("Incubation"), measures=c("Observed")) + 
  geom_boxplot(aes(fill = Incubation), color = "black", lwd = 0.7) + 
  ggtitle("Cyanobacteria in LAC crust type") + 
  #stat_compare_means(method = "t.test", label.y = 300) + 
  annotate("text", x = 3, y = 2000, label = "ANOVA, p = 0.0455") +
  theme_pubr(border= TRUE, legend = c("none")) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_colour_hue(l = 58) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_text(data=LABELS, aes(x=LABELS$Incubation, y = LABELS$ylabel , label = LABELS$Letters))
physeq.plot.richness.incubation

#dev.off()
``` 