Title: Fungal diversity analysis
Author: Teeratat Kaewjon
Updated: 5/18/2024
---
output:
  word_document: default
  html_document: default
---

```{r warning=FALSE, message=FALSE}
library(ape)
library(vegan)
library(plyr)
library(dplyr)
library(scales)
library(grid)
library(reshape2)
library(phyloseq)
library(magrittr)
library(ggplot2)
library(ggpubr)
library(data.table)
library(tidyr)
library(tidyverse)
library(multcompView)
library(car)
```

```{r}
otus <- read.table("D:/Biocrust_Reawakening/Github/Fungi(ITS)/Data/CrustTemp2ITSasvUN3.otu_table_fix.txt",header=T,sep="\t",row.names=1)
otumat <- as(as.matrix(otus), "matrix")
OTU <- otu_table(otumat, taxa_are_rows = TRUE)
```

```{r}
taxmat.fix <- read.table("D:/Biocrust_Reawakening/Github/Fungi(ITS)/Data/tax_fun_fix.csv", header=T,sep=",",row.names=1)
taxmat.fix <- as(as.matrix(taxmat.fix),"matrix")
TAX.fix <- tax_table(taxmat.fix)

physeqITS <- phyloseq(OTU,TAX.fix,sampleData)
physeqITS
#tax_table(physeqITS)
```

```{r}
meta <- read.table("./Fungi_data/CrustTemp2ITSasvUN3.mapping_file_fix.txt",header=TRUE,row.names=1,sep="\t",stringsAsFactors=FALSE)
sampleData <- sample_data(meta)
```

```{r}
physeqITS <- subset_taxa(physeqITS, Kingdom == "Fungi")
physeqITS

physeq.prune = prune_taxa(taxa_sums(physeqITS) > 1, physeqITS)
physeq.prune
```

#### Alpha diversity

```{r}
sample_data(physeq.LAC)$Incubation = factor(sample_data(physeq.LAC)$Incubation, levels = c("0.05", "1", "24", "48", "96"))

sample_data(physeq.CLC)$Incubation = factor(sample_data(physeq.CLC)$Incubation, levels = c("0.05", "1", "24", "48", "96"))
```

```{r}
alpha.diversity = estimate_richness(physeq.CLC, measures = c("Shannon"))
data.anova = cbind(sample_data(physeq.CLC), alpha.diversity)
#leveneTest(Observed ~ Incubation, data = data.anova)
physeq.anova = aov(Shannon ~ Incubation, data.anova)
summary(physeq.anova)
```

```{r}
tukey.ps = TukeyHSD(x=physeq.anova, 'Incubation', conf.level = 0.95)

generate_label_df <- function(tukey.ps, variable){
 
     # Extract labels and factor levels from Tukey post-hoc 
     Tukey.levels <- tukey.ps[[variable]][,4]
     Tukey.labels <- data.frame(multcompLetters(Tukey.levels)['Letters'])
     
     #I need to put the labels in the same order as in the boxplot :
     Tukey.labels$treatment=rownames(Tukey.labels)
     Tukey.labels=Tukey.labels[order(Tukey.labels$treatment) , ]
     return(Tukey.labels)
     }

LABELS=generate_label_df(tukey.ps, 'Incubation')
names(LABELS) = c('Letters','Incubation')
```

```{r}
LABELS
```

```{r}
ylabel <- data.frame("ylabel" = c(4, 4, 4, 3.5, 3.5)) #LAC surface
LABELS$ylabel<-ylabel$ylabel
```

```{r}
tiff("D:/Biocrust_Reawakening/New_data/Fungi/Figures/Fun_Alpha_CLC_Shannon.tiff", units="in", width = 4.5, height = 6, res = 600 )

#pdf("D:/Biocrust_Reawakening/Github/Fungi(ITS)/Figures/BAC_Alpha_CLC_Shannon.pdf",width = 8.5, height = 5.5)

custom_palette <- c("0.05" = "#F8766D", "1" = "#A3A500", "24" = "#00BF7D", "48" = "#00B0F6", "96" = "#E76BF3")

physeq.plot.richness.incubation <- plot_richness(physeq.CLC, x = "Incubation", color = "Incubation", measures = c("Shannon")) + 
  geom_boxplot(aes(fill = Incubation), color = "black", lwd = 0.7) + 
  ggtitle("Fungal Alpha Diversity of CLC crust type (Shannon)") + 
  annotate("text", x = 3, y = 4.5, label = "ANOVA, p = 0.0141") +
  theme_pubr(border = TRUE, legend = "none") + 
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_colour_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  geom_text(data = LABELS, aes(x = Incubation, y = ylabel, label = Letters))

physeq.plot.richness.incubation
```

### Beta diversity with NMDS plot analysis

```{r}
sample_data(physeq.prune)$Incubation = factor(sample_data(physeq.prune)$Incubation, levels = c("0.05", "1", "24", "48", "96"))
sample_data(physeq.prune)$Crusttype = factor(sample_data(physeq.prune)$Crusttype, levels = c("CLC", "LAC"))

sample_data(physeq.LAC)$Incubation = factor(sample_data(physeq.LAC)$Incubation, levels = c("0.05", "1", "24", "48", "96"))

sample_data(physeq.CLC)$Incubation = factor(sample_data(physeq.CLC)$Incubation, levels = c("0.05", "1", "24", "48", "96"))
```

```{r}
physeq_ord <- ordinate(physeq.prune,method = "NMDS",distance =  "bray")
```

```{r}
ps.dist.all = phyloseq::distance(physeq.prune, "bray")
```

```{r}
adonis2(ps.dist.all ~Incubation+Crusttype, as(sample_data(physeq.prune),"data.frame"))
```

```{r}
#tiff("D:/Biocrust_Reawakening/New_data/Fungi/Figures/Fun_Beta_CLC_NMDS.tiff", units="in", width = 6, height = 4.5, res = 600 )
plot

pslayer = plot_ordination(physeq.prune, physeq_ord, type = "samples", color = "Incubation", shape = "Crusttype") + ggtitle("Fungal Beta Diversity") + 
  annotate("text", x = 1.6, y = 1.2, label = "PERMANOVA, p = 0.024") +
  geom_point(size=4) + 
  scale_colour_manual(values =  c("#F8766D" , "#A3A500" , "#00BF7D",  "#00B0F6", "#E76BF3")) + 
  theme_pubr(legend = "right", border = TRUE) + 
  theme(plot.title = element_text(hjust = 0.5))

pslayer
```
